const DSA_TOPICS = [
  'Basics & Math',
  'Arrays & Hashing',
  'Two Pointers',
  'Strings',
  'Recursion',
  'Sorting',
  'Binary Search',
  'Prefix & Suffix Sum',
  'Sliding Window',
  'Linked List',
  'Stack',
  'Queue',
  'Trees',
  'Binary Trees',
  'Binary Search Trees',
  'Heap / Priority Queue',
  'Greedy',
  'Backtracking',
  'Dynamic Programming',
  'Graphs',
  'Tries',
  'Bit Manipulation',
  'Segment Tree',
  'Disjoint Set Union',
  'Advanced Graphs',
];

const DSA_QUESTIONS = [
  {
    id: 'two-sum',
    topic: 'Arrays & Hashing',
    title: 'Two Sum',
    difficulty: 'Easy',
    points: 5,
    description: 'Given an array of integers and a target, return indices of the two numbers that add up to the target.',
    constraints: '2 <= nums.length <= 10^4',
    inputFormat: 'First line: n, target\nSecond line: n integers',
    outputFormat: 'Return the indices as a list.',
    sampleInput: '4 9\n2 7 11 15',
    sampleOutput: '[0, 1]',
    explanation: 'Use a hash map to track seen values and their indices.',
    starterCode: {
      c: '#include <stdio.h>\n\nint main() {\n  return 0;\n}\n',
      'c++': '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n  return 0;\n}\n',
      java: 'class Solution {\n  public static void main(String[] args) {}\n}\n',
      python: 'def solve():\n    pass\n\nif __name__ == "__main__":\n    solve()\n',
    },
  },
  {
    id: 'binary-search',
    topic: 'Binary Search',
    title: 'Binary Search',
    difficulty: 'Easy',
    points: 5,
    description: 'Search for a target value in a sorted array.',
    constraints: '1 <= n <= 10^5',
    inputFormat: 'First line: n, target\nSecond line: n integers',
    outputFormat: 'Print the index of the target or -1.',
    sampleInput: '5 4\n1 2 3 4 5',
    sampleOutput: '3',
    explanation: 'Apply binary search by shrinking the search interval.',
    starterCode: {
      c: '#include <stdio.h>\n\nint main() {\n  return 0;\n}\n',
      'c++': '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n  return 0;\n}\n',
      java: 'class Solution {\n  public static void main(String[] args) {}\n}\n',
      python: 'def solve():\n    pass\n\nif __name__ == "__main__":\n    solve()\n',
    },
  },
  {
    id: 'merge-intervals',
    topic: 'Sorting',
    title: 'Merge Intervals',
    difficulty: 'Medium',
    points: 10,
    description: 'Merge overlapping intervals in a list.',
    constraints: '1 <= intervals.length <= 10^4',
    inputFormat: 'First line: n\nNext n lines: start end',
    outputFormat: 'Print merged intervals.',
    sampleInput: '4\n1 3\n2 6\n8 10\n15 18',
    sampleOutput: '1 6\n8 10\n15 18',
    explanation: 'Sort intervals by start and merge when overlap occurs.',
    starterCode: {
      c: '#include <stdio.h>\n\nint main() {\n  return 0;\n}\n',
      'c++': '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n  return 0;\n}\n',
      java: 'class Solution {\n  public static void main(String[] args) {}\n}\n',
      python: 'def solve():\n    pass\n\nif __name__ == "__main__":\n    solve()\n',
    },
  },
  {
    id: 'lucky-number',
    topic: 'Basics & Math',
    title: 'Lucky Number',
    difficulty: 'Easy',
    points: 5,
    description: 'Determine whether a positive integer is lucky if it is divisible by 7 or contains digit 7.',
    constraints: '1 <= N <= 10^9',
    inputFormat: 'The first line contains a single integer N.',
    outputFormat: 'Print Lucky if the number is lucky; otherwise print Not Lucky.',
    sampleInput: '17',
    sampleOutput: 'Lucky',
    explanation: 'A number is lucky when it is divisible by 7 or contains the digit 7. Example: 17 is lucky because it contains 7.',
    starterCode: {
      c: '#include <stdio.h>\n\nint main() {\n  int n;\n  scanf("%d", &n);\n  if (n % 7 == 0 || n % 10 == 7) {\n    printf("Lucky");\n  } else {\n    printf("Not Lucky");\n  }\n  return 0;\n}\n',
      'c++': '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n  int n;\n  cin >> n;\n  bool lucky = (n % 7 == 0);\n  int x = n;\n  while (x > 0) {\n    if (x % 10 == 7) {\n      lucky = true;\n      break;\n    }\n    x /= 10;\n  }\n  cout << (lucky ? "Lucky" : "Not Lucky");\n  return 0;\n}\n',
      java: 'import java.util.Scanner;\n\npublic class Solution {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt();\n    boolean lucky = (n % 7 == 0);\n    int x = n;\n    while (x > 0) {\n      if (x % 10 == 7) {\n        lucky = true;\n        break;\n      }\n      x /= 10;\n    }\n    System.out.println(lucky ? "Lucky" : "Not Lucky");\n  }\n}\n',
      python: 'n = int(input().strip())\n\nlucky = (n % 7 == 0) or ("7" in str(n))\nprint("Lucky" if lucky else "Not Lucky")\n',
    },
  },
];

const getQuestionsByTopic = (topic) => DSA_QUESTIONS.filter((q) => q.topic === topic);
const getAllQuestions = () => DSA_QUESTIONS;
const getQuestionById = (id) => DSA_QUESTIONS.find((q) => q.id === id) || null;

module.exports = {
  DSA_TOPICS,
  DSA_QUESTIONS,
  getQuestionsByTopic,
  getAllQuestions,
  getQuestionById,
};
